markdown: kramdown
rdiscount:
  extensions: [smart]
url: http://www.opencompany.org/
plugins:
  - jekyll-multiple-languages-plugin
languages: ["en", "fr", "pl"]
# Here is the configuration for sharing buttons.
sharing :
  provider : ["like", "tweet", "plusone", "linkedin"]
  twitter :
    size :
    via :
    count :
  facebook :
    layout : button_count
    font :
    faces : false
    width : 90
  googleplus :
    size : medium
    width :
    annotation : bubble
  linkedin :
    counter : right

# The code that deal with the provider _includes/sharing-providers/
# The code that includes the right bits _includes/sharing
